packaging_format = 2

id = "wireguard_client"
name = "WireGuard Client"
description.en = "Connect your server to VPNs as a client"
description.fr = "Connectez votre serveur à des VPN en tant que client"

version = "0.3~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.wireguard.com/"
cpe = "cpe:2.3:a:pfsense:pfsense-pkg-wireguard"
fund = "https://www.wireguard.com/donations/"

[integration]
yunohost = ">= 11"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.apt]
    packages = "wireguard"
