#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE SETTINGS
#=================================================

# Needed for the config panel
ynh_app_setting_set --key=interfaces --value=""

#=================================================
# CONFIGURING WIREGUARD
#=================================================

mkdir -p $install_dir

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create dedicated systemd configs for starting and monitoring WireGuard's configurations
ynh_config_add --template="wireguard_client@.service" --destination="/etc/systemd/system/$app@.service"
systemctl daemon-reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed. Use its configuration panel to create new VPN interfaces."
