#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Needed for the config panel
ynh_app_setting_set --key=interfaces --value=""

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create dedicated systemd configs for starting and monitoring WireGuard's configurations
ynh_config_add --template="wireguard_client@.service" --destination="/etc/systemd/system/$app@.service"
systemctl daemon-reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed. Use its configuration panel to create new VPN interfaces."
