#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the services from the list of services known by Yunohost (added from `yunohost service add`)
for file in $data_dir/*.conf ; do
    i=$(basename $file .conf)
    systemctl disable --quiet --now wireguard_client@$i.service || true
    yunohost service remove wireguard_client@$i || true
done

ynh_safe_rm "/etc/systemd/system/wireguard_client@.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
