#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the services from the list of services known by Yunohost (added from `yunohost service add`)
for file in $install_dir/*.conf ; do
    i=$(basename $file .conf)
    systemctl disable --quiet --now wireguard_client@$i.service || true
    yunohost service remove wireguard_client@$i || true
done

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info "Stopping and removing the systemd service..."

ynh_safe_rm "/etc/systemd/system/wireguard_client@.service"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Removal of $app completed"
