#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_print_info --message="Restoring the app main directory..."

ynh_restore_file --origin_path="$install_dir"

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_print_info --message="Restoring the systemd configuration..."

ynh_restore_file --origin_path=/etc/systemd/system/wireguard_client@.service
systemctl daemon-reload

#=================================================
# START AND INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_print_info --message="Integrating services in YunoHost..."

integrate_services

#=================================================
# GENERIC FINALIZATION
#=================================================

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info --message="Restoration completed for $app."
