#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_print_info "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_print_info "Restoring $app's systemd service..."

ynh_restore /etc/systemd/system/wireguard_client@.service
systemctl daemon-reload

#=================================================
# START AND INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_print_info "Integrating services in YunoHost..."

integrate_services

#=================================================

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Restoration completed for $app."
