#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_print_info "Ensuring downward compatibility..."

# Making sure the current config panel is not being overidden by the upgrade
# We copy the current over the temporary one deployed during the upgrade
# It is being copied back over after the end of this upgrade script
cp /etc/yunohost/apps/$app/config_panel.toml $YNH_APP_BASEDIR

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_print_info "Upgrading systemd configuration..."

# Create dedicated systemd configs for starting and monitoring WireGuard's configuration
ynh_config_add --template="wireguard_client@.service" --destination="/etc/systemd/system/$app@.service"
systemctl daemon-reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Upgrade of $app completed."
