#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_print_info "Ensuring downward compatibility..."

# Making sure the current config panel is not being overidden by the upgrade
# We copy the current over the temporary one deployed during the upgrade
# It is being copied back over after the end of this upgrade script
cp /etc/yunohost/apps/$app/config_panel.toml $YNH_APP_BASEDIR

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_print_info "Upgrading systemd configuration..."

# Create dedicated systemd configs for starting and monitoring WireGuard's configuration
ynh_config_add --template="wireguard_client@.service" --destination="/etc/systemd/system/$app@.service"
systemctl daemon-reload

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app: "$install_dir"
#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Upgrade of $app completed."
