#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_print_info --message="Ensuring downward compatibility..."

# Making sure the current config panel is not being overidden by the upgrade
# We copy the current over the temporary one deployed during the upgrade
# It is being copied back over after the end of this upgrade script
cp /etc/yunohost/apps/$app/config_panel.toml $YNH_APP_BASEDIR

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_print_info --message="Upgrading systemd configuration..."

# Create dedicated systemd configs for starting and monitoring WireGuard's configuration
ynh_add_config --template="wireguard_client@.service" --destination="/etc/systemd/system/$app@.service"
systemctl daemon-reload

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info --message="Upgrade of $app completed."
